<?php
    $aAccessId=Array();
    $aAccessId[]="1";
    $aAccessId[]="2";
    $aAccessId[]="3";
    include( "auth.inc" );

    $bIsPm=false;
	$bIsSu=false;
	$bIsPro=false;
	for( $i=0; $i<count($aGruppe); $i++ ) {
		if( $aGruppe[$i]==2 )
			$bIsPm=true;
		if( $aGruppe[$i]==3 )
			$bIsSu=true;	
		if( $aGruppe[$i]==1 )
			$bIsPro=true;
	}

?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
    <META HTTP-EQUIV="pragma" CONTENT="no-cache">
    <title>Staatssicherheit</title>
    <link rel="stylesheet" type="text/css" href="/css/stasi.css">
    <script type="text/javascript" language="JavaScript" src="/js/submit.js"></script>
    <script type="text/javascript" language="JavaScript">
       function showMaProjekt( nMaId, sBegin, sEnd, sDate ) {
            if( sBegin=="" )
                sBegin=-1;
            if( sEnd=="" )
                sEnd=-1;
            sUrl = "ma_projekt.phtml?urlMaId=" + nMaId + "&urlBegin=" + sBegin + "&urlEnd=" + sEnd + "&urlDate=" + sDate;
            document.location.href=sUrl;
        }
        function printView( sBegin, sEnd, sDate ) {
            if( sBegin=="" )
                sBegin=-1;
            if( sEnd=="" )
                sEnd=-1;
            var sUrl = "p_ma.phtml?urlBegin=" + sBegin + "&urlEnd=" + sEnd + "&urlDate=" + sDate;
            printWindow = window.open( sUrl,"printWindow","toolbar=yes,location=no,directories=no,status=no,menubar=yes,scrollbars=auto,width=800,height=600,resizable=yes");
            if( window.focus )
                printWindow.focus();
        }
        function cmbBeginClicked() {
				sEndText=getSelectedCmbText( this, "fmTime", "cmbBegin" );
				selectCmbByText( this, "fmTime", "cmbEnd", sEndText);
			}
    </script>
</head>
<body>
<table width="600"><tr><td class="hintergrund"> 
<?php
    include( "auswertung/view/v_ma.inc" );
    include( "auswertung/time_form.inc" );
    $sBegin;
    $sEnd;
    
    getTimeValues();
    printTimeTable();
    
    $ma_view = new v_ma( $sBegin,$sEnd );
    $ma_view->ma->sDate=$sDate;

    if( !$bIsSu && !$bIsPm  )
		$ma_view->ma->nMaId=$nMaId;

    echo $ma_view->getTable();
?>
</td></tr></table>
</body>
</html>