<?php
	$aAccessId=Array();
	$aAccessId[]="1";
	$aAccessId[]="2";
	$aAccessId[]="3";
	include( "auth.inc" );

	$bIsPm=false;
	$bIsSu=false;
	$bIsPro=false;
	for( $i=0; $i<count($aGruppe); $i++ ) {
		if( $aGruppe[$i]==2 )
			$bIsPm=true;
		if( $aGruppe[$i]==3 )
			$bIsSu=true;	
		if( $aGruppe[$i]==1 )
			$bIsPro=true;
	}
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<META HTTP-EQUIV="pragma" CONTENT="no-cache">
	<title>Staatssicherheit</title>
	<link rel="stylesheet" type="text/css" href="/css/stasi.css">
	<script type="text/javascript" language="JavaScript" src="/js/submit.js"></script>
	<script type="text/javascript" language="JavaScript">
		function showDetail( nProjektId ) {
			alert( "noch nicht implementiert" );
		}
		function cmbBeginClicked() {
			sEnd=getSelectedCmbValue( this, "fmTime", "cmbBegin" ).substring( 0, 4 ) + "-" + getSelectedCmbValue( this, "fmTime", "cmbBegin" ).substring( 5, 7 ) + "-31";
			selectCmbByValue( this, "fmTime", "cmbEnd", sEnd);
		}
	</script>
</head>
<body>
<table width="600">
<tr>
	<th align="left" class="print"></th>
</tr>
<tr><td class="hintergrund"> 
<?php
	include( "auswertung/print/p_projekt_schritt_ma.inc" );
	include( "auswertung/time_form.inc" );
	
	getTimeValues(); 
	
	if( $urlSchrittId!="" ) {
		$p_projekt_schritt_ma = new p_projekt_schritt_ma( $urlSchrittId, $sBegin,$sEnd );
		$p_projekt_schritt_ma->projekt_schritt_ma->sDate=$sDate;
		/*
		if( !$bIsSu  )
			$p_projekt_schritt_ma->projekt_ma->nMaId=$nMaId;
		if( $bIsPm )
			$p_projekt_schritt_ma->projekt_ma->nPmId=$nMaId;
		*/
		if( !$bIsSu && !$bIsPm  )
			$p_projekt_schritt_ma->projekt_ma->nMaId=$nMaId;
		echo $p_projekt_schritt_ma->getTable();
	}
	else
		echo "Keine Schritt Id vorhanden. Auswertung nicht moeglich.";
?>
</td></tr></table>
</body>
</html>