<?php
	$aAccessId=Array();
	$aAccessId[]="1";
	$aAccessId[]="2";
	$aAccessId[]="3";
	include( "auth.inc" );

	$bIsPm=false;
	$bIsSu=false;
	$bIsPro=false;
	for( $i=0; $i<count($aGruppe); $i++ ) {
		if( $aGruppe[$i]==2 )
			$bIsPm=true;
		if( $aGruppe[$i]==3 )
			$bIsSu=true;	
		if( $aGruppe[$i]==1 )
			$bIsPro=true;
	}
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<META HTTP-EQUIV="pragma" CONTENT="no-cache">
	<title>Staatssicherheit</title>
	<link rel="stylesheet" type="text/css" href="/css/stasi.css">
	<script type="text/javascript" language="JavaScript" src="/js/submit.js"></script>
	<script type="text/javascript" language="JavaScript">
		function printView( nMaId, nSchrittId, sBegin, sEnd, sDate ) {
			if( sBegin=="" )
				sBegin=-1;
			if( sEnd=="" )
				sEnd=-1;
			var sUrl = "p_schritt_detail.phtml?urlMaId=" + nMaId + "&urlSchrittId=" + nSchrittId + "&urlBegin=" + sBegin + "&urlEnd=" + sEnd + "&urlDate=" + sDate;
			printWindow = window.open( sUrl,"printWindow","toolbar=yes,location=no,directories=no,status=no,menubar=yes,scrollbars=auto,width=800,height=600,resizable=yes");
			if( window.focus )
				printWindow.focus();
		}
		function openEditWindow( nArbeitId ) {
			var sUrl = "../stunden/editArbeit.phtml?urlArbeitId=" + nArbeitId;
			editWindow = window.open( sUrl,"editWindow","toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=auto,width=470,height=200,resizable=yes");
			if( window.focus )
				editWindow.focus();
		}
		function cmbBeginClicked() {
			sEndText=getSelectedCmbText( this, "fmTime", "cmbBegin" );
			selectCmbByText( this, "fmTime", "cmbEnd", sEndText);
		}
	</script>
</head>
<body>
<table width="600"><tr><td class="hintergrund"> 
<?php
	include( "auswertung/view/v_schritt_detail.inc" );
	include( "auswertung/time_form.inc" );
	
	getTimeValues();
	
	setValue( "urlSchrittId",$urlSchrittId ); 
	setValue( "urlMaId",$urlMaId ); 
	printTimeTable();
	
	if( $urlSchrittId!="" ) {
		$v_schritt_detail = new v_schritt_detail( $urlMaId, $urlSchrittId, $sBegin, $sEnd );
		$v_schritt_detail->schritt_detail->sDate=$sDate;
		/*
		sicherheit unnoetig, da nur berechtigte an den link gelangen
		if( !$bIsSu  )
			$v_schritt_detail->schritt_detail->nMaId=$nMaId;
		if( $bIsPm )
			$v_schritt_detail->schritt_detail->nPmId=$nMaId;
		if( !$bIsSu && !$bIsPm  )
			$v_schritt_detail->schritt_detail->nMaId=$nMaId;
		*/
		echo $v_schritt_detail->getTable();
	}
	else
		echo "Keine Schritt Id vorhanden. Auswertung nicht moeglich.";
?>
</td></tr></table>
</body>
</html>