<?php
	$bIsLocal=true;
	
	$aAccessId=Array();
	$aAccessId[]="2";
	$aAccessId[]="3";
	include( "auth.inc" );
	
	include( "arbeit.inc" );
?>
	
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	<link rel="stylesheet" type="text/css" href="/css/stasi.css">
	<script type="text/javascript" language="JavaScript" src="/js/submit.js"></script>
	<script type="text/javascript" language="JavaScript">
		function closeWindow() {
			if( opener )
				opener.location.reload();
			window.close();
		}
	</script>
	<?php
	
	$bDebug="false";
	if( $txtDelSchrittId!="" ) {
		//set db connection:
		if( !$bIsDbConnected )
			if( $bIsLocal )
				include("stasi_db_settings.inc");
			else
				include(  "stasi_db_settings.inc" );
		
		$sqlDeleteArbeit = "delete from arbeit where arbeit.schritt_id=$txtDelSchrittId";
		mysql_query( $sqlDeleteArbeit )
			or die( printError( $sqlDeleteArbeit ) );
		if( $bDebug=="true" )
			echo $sqlDeleteArbeit . "<br>";
		
		$sqlDeleteSchritt = "delete from schritt where schritt_id=$txtDelSchrittId";
		mysql_query( $sqlDeleteSchritt )
			or die( printError( $sqlDeleteSchritt ) );
		if( $bDebug=="true" )
			echo $sqlDeleteSchritt . "<br>";
			
		echo "<script type=\"text/javascript\" language=\"JavaScript\">";
		echo "	closeWindow();";
		echo "</script>";
	}
?>
</head>
<body>
<table width="100%" height="100%">
<tr>
<td align="center" valign="middle">
<form name="fmDeleteSchritt" action="<?php echo "$PHP_SELF" ?>" method="post">
	<input type="hidden" name="txtDelSchrittId" type="hidden" value="<?php echo $txtSchrittId ?>">
	<table border="0" CELLPADDING="3" CELLSPACING="1" bgcolor="#666666">
		<tr>
			<th align="left" colspan="2">Soll der Arbeitschritt <?php echo $txtBezeichnung ?> gel&ouml;scht werden? Achtung, es werden auch alle gespeicherten Stunden f&uuml;r diesen Arbeitsschritt gel&ouml;scht.</td>
		</tr>
		<tr>
			<td><input type="submit" value="Ok"></td>
			<td align='right'><input type="button" value="Cancel" onClick="window.close();"></td>
		</tr>
	</table>
</form>
</td>
</tr>
</table>
</body>
</html>
