<?php
	$bIsLocal=true;
	
	$aAccessId=Array();
	$aAccessId[]="1";
	$aAccessId[]="2";
	$aAccessId[]="3";
	include( "auth.inc" );
?>
	
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	<title>Staatssicherheit</title>
	<link rel="stylesheet" type="text/css" href="/css/stasi.css">
	<script type="text/javascript" language="JavaScript" src="/js/submit.js"></script>
	<script type="text/javascript" language="JavaScript">
		function closeWindow() {
			if( opener )
				opener.location.reload();
			window.close();
		}
	</script>
	<?php
	$bDebug="true";
	if( $txtDelArbeitId!="" ) {
		//set db connection:
		if( !$bIsDbConnected )
			if( $bIsLocal )
				include("stasi_db_settings.inc");
			else
				include(  "stasi_db_settings.inc" );
		
		//loeschen tabelle arbeit
		$sqlDeleteArbeit = "delete from arbeit where arbeit_id=$txtDelArbeitId";
		mysql_query( $sqlDeleteArbeit )
			or die( printError( $sqlDeleteArbeit ) );
		if( $bDebug=="true" )
			echo $sqlDeleteArbeit . "<br>";
			
		echo "<script type=\"text/javascript\" language=\"JavaScript\">";
		echo "	closeWindow();";
		echo "</script>";
	}
?>
</head>
<body>
<table width="447"><tr><td class="hintergrund">
<table border="0" cellpadding="1" cellspacing="1" width="100%">
<tr>
<td align="center" valign="middle">
<form name="fmDeleteArbeit" action="<?php echo "$PHP_SELF" ?>" method="post">
	<input type="hidden" name="txtDelArbeitId" type="hidden" value="<?php echo $urlArbeitId ?>">
	<table border="0" CELLPADDING="1" CELLSPACING="1" bgcolor="#666666">
		<tr>
			<th align="left" colspan="2">Soll der Arbeitsschritt gel&ouml;scht werden?</td>
		</tr>
		<tr>
			<td><input type="submit" value="Ok"></td>
			<td align='right'><input type="button" value="Cancel" onClick="window.close();"></td>
		</tr>
	</table>
</form>
</td>
</tr>
</table>
</td></tr></table>
</body>
</html>
