<?php
	$bIsLocal=true;
	
	$aAccessId=Array();
	$aAccessId[]="1";
	$aAccessId[]="2";
	$aAccessId[]="3";
	include(  "auth.inc" );	
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<META HTTP-EQUIV="pragma" CONTENT="no-cache">
<html>
<head>
	<title>Staatssicherheit</title>
</head>
<frameset rows="40,*">
	<frame src="menu.phtml" name="top" noresize border=0 frameborder=0 framespacing=0 scrolling=no>
	<frame src="stunden/index.phtml" name="middle" noresize border=0 frameborder=0 framespacing=0 scrolling=auto>
</frameset>
</html>
