			<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
			  <html>
			  <head>
				<title>Staatssicherheit</title>
				<link rel="stylesheet" type="text/css" href="/css/stasi.css">
				<script type="text/javascript" language="JavaScript" src="/js/submit.js"></script>
			 </head>
			  <body>
			  	<form>
				<table width="195"><tr><td class="hintergrund"> 
				<table border="0" cellpadding="1" cellspacing="1" width="100%">
					<tr>
						<th>Staatssicherheit</th>
					</tr>
					<tr>
						<td align="center">Zugang verweigert</td>
					</tr>
					<tr>
						<td align="center"><input type="button" value="  neuer Login   " onClick="opener.document.fmIrl.submit();window.close();"></td>
					</tr>
				</table>
				</td></tr></table>
				</form>
				</body>
			  </html>
