<?php
	$bIsLocal=true;
	
	$aAccessId=Array();
	$aAccessId[]="1";
	$aAccessId[]="2";
	$aAccessId[]="3";
	include(  "auth.inc" );
	
	$bIsSu=false;
	for( $i=0; $i<count($aGruppe); $i++ ) {
		if( $aGruppe[$i]==3 )
			$bIsSu=true;	
	}
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<META HTTP-EQUIV="pragma" CONTENT="no-cache">
<title>URLAUB</title>
<link rel="stylesheet" type="text/css" href="/css/stasi.css">
<script type="text/javascript" language="JavaScript" src="/js/submit.js"></script>

<script type="text/javascript" language="JavaScript">
function checkAndSubmit(){
//	alert("loeschen");
	document.fmArbeit.txtLoeschenIsSubmit.value="true";
	document.fmArbeit.submit();

}
<?php
//set db connection:
if( !$bIsDbConnected )
	include( "stasi_db_settings.inc");
function setValues() {
	global $nMitarbeiterId, $txtArbeitId,$cmbSchritt,$cmbMitarbeiter,$txtMaId, $txtJahr_von, $txtMonat_von, $txtTag_von, $txtJahr_bis, $txtMonat_bis, $txtTag_bis;

	$nArbeitId=$txtArbeitId;
	$nSchrittId=$cmbSchritt;	
	$nMaId=$txtMaId;
		
	if( $txtJahr_von>=70 ) {
		$txtJahr_von="19" . $txtJahr_von;
	}
	else if( $txtJahr_bis>=70 ) {
		$txtJahr_bis="19" . $txtJahr_bis;
	}
	else if ( $txtJahr_von<70 ) {
		$txtJahr_von="20" . $txtJahr_von;
	}
	else if ( $txtJahr_bis<70 ) {
		$txtJahr_bis="20" . $txtJahr_bis;
	}
}
function checkValues() {
//	echo "alert('checkValues aufgerfufen')\n";
	global $nMitarbeiterId, $txtArbeitId,$cmbSchritt,$cmbMitarbeiter, $txtMaId, $txtJahr_von, $cmbMonat_von, $cmbTag_von, $txtJahr_bis, $cmbMonat_bis, $cmbTag_bis, $sTimestamp_von, $sTimestamp_bis, $sMySqlDate_von, $sMySqlDate_bis;           
	
	if($txtJahr_von!="" && $cmbMonat_von!="monatvon" && $cmbTag_von!="tagvon" && $txtJahr_bis!="" && $cmbMonat_bis!="monatbis" && $cmbTag_bis!="tagbis") {
		$sTimestamp_von = mktime(0,0,0,date($cmbMonat_von),date($cmbTag_von),date($txtJahr_von));
		$sTimestamp_bis = mktime(0,0,0,date($cmbMonat_bis),date($cmbTag_bis),date($txtJahr_bis));

		if($sTimestamp_bis < $sTimestamp_von) {
			echo "alert('falsche daten eingegeben')\n";
			return false;
		}
		else{
			return true;	
		}
	}
	else{
		echo "alert('keine daten eingegeben')\n";
		return false;
	}
}

function action() {
	global $nMitarbeiterId, $txtIsSubmit, $txtLoeschenIsSubmit, $txtArbeitId,$cmbSchritt,$cmbMitarbeiter, $txtMaId, $txtJahr_von, $cmbMonat_von, $cmbTag_von, $txtJahr_bis, $cmbMonat_bis, $cmbTag_bis, $sTimestamp_von, $sTimestamp_bis, $sMySqlDate_von, $sMySqlDate_bis;
	if( ($txtIsSubmit!="true") && ($txtLoeschenIsSubmit!="true")){
//		echo "alert('txtIsSubmit und txtLoeschenIsSubmit is not true')\n";	
		return;
	} 
	else {
			setValues();
//			echo "alert('set values aufgerufen')\n";	
			
		if ( checkValues() ) {
			if( $txtLoeschenIsSubmit!="true" ){	
				$sTimestamp_von = mktime(0,0,0,date($cmbMonat_von),date($cmbTag_von),date($txtJahr_von));
				$sTimestamp_bis = mktime(0,0,0,date($cmbMonat_bis),date($cmbTag_bis),date($txtJahr_bis));
				$nDauer = 8*3600; 
				while($sTimestamp_von<=$sTimestamp_bis){
					$nTag	=date("w",$sTimestamp_von);
					$sMySqlDate_von = date("Y-m-d",$sTimestamp_von);				
					$sMySqlDate_bis = date("Y-m-d",$sTimestamp_bis);
//					echo "alert($nTag)\n";
					if ($cmbMitarbeiter=="") {
//						echo "alert('sich selber eintragen')\n";
						if($nTag!=0 && $nTag!=6){
							$sqlInsert="insert into arbeit (ma_id,schritt_id,datum,dauer) values ($txtMaId,$cmbSchritt,'$sMySqlDate_von',$nDauer)";
//							echo "alert('$sqlInsert')\n";
							mysql_query( $sqlInsert )
								or die( dbError( $sqlInsert ) );
 						}
 					}
 					else {
// 					echo "alert('andere menschen eintragen')\n";
 						if($nTag!=0 && $nTag!=6){
							$sqlInsert="insert into arbeit (ma_id,schritt_id,datum,dauer) values ($cmbMitarbeiter,$cmbSchritt,'$sMySqlDate_von',$nDauer)";
//							echo "alert('$sqlInsert')\n";
							mysql_query( $sqlInsert )
								or die( dbError( $sqlInsert ) );
 						}
					}				
					$sTimestamp_von += 86400;
				}
			}
			else {
				$sTimestamp_von = mktime(0,0,0,date($cmbMonat_von),date($cmbTag_von),date($txtJahr_von));
				$sTimestamp_bis = mktime(0,0,0,date($cmbMonat_bis),date($cmbTag_bis),date($txtJahr_bis));
				$nDauer = 8*3600; 
				while($sTimestamp_von<=$sTimestamp_bis){
					$nTag	=date("w",$sTimestamp_von);
					$sMySqlDate_von = date("Y-m-d",$sTimestamp_von);				
					$sMySqlDate_bis = date("Y-m-d",$sTimestamp_bis);
//					echo "alert($nTag)\n";
					if ($cmbMitarbeiter=="") {
//						echo "alert('eigenen eintrag loeschen')\n";
						if($nTag!=0 && $nTag!=6){
							$sqlDelete="delete from arbeit WHERE ma_id=$txtMaId AND schritt_id=$cmbSchritt AND datum='$sMySqlDate_von' AND dauer=$nDauer";
//							echo "alert('$sqlDelete')\n";
							mysql_query( $sqlDelete )
								or die( dbError( $sqlDelete ) );
 						}
 					}
 					else {
//					echo "alert('eintrag von anderen loeschen eintragen')\n";
 						if($nTag!=0 && $nTag!=6){
							$sqlDelete="delete from arbeit WHERE ma_id=$cmbMitarbeiter AND schritt_id=$cmbSchritt AND datum='$sMySqlDate_von' AND dauer=$nDauer";
//							echo "alert('$sqlDelete')\n";
							mysql_query( $sqlDelete )
								or die( dbError( $sqlDelete ) );
 						}
					}				
					$sTimestamp_von += 86400;
				}
			}
		}
	}
}
			$bDebug="true";
			$nCmbSize=2;
			//set db connection:
			if( !$bIsDbConnected )
				include("stasi_db_settings.inc");
			$sHeader = "Sag die Wahrheit !";
			if( $txtArbeitId=="" ){
				action();
			}
			else{
			return;
			}
				
			
?>
</script>

</head>
<body>
<form name="fmArbeit" action="<?php echo "$PHP_SELF" ?>" method="post">
<input name="txtMaId" type="hidden" value="<?php echo $nMaId ?>">
<input name="txtArbeitId" type="hidden" value="<?php if( $urlArbeitId!="" ) echo $nArbeitId ?>">
<input name="txtIsSubmit" type="hidden" value="true">
<input name="txtLoeschenIsSubmit" type="hidden">
<table width="780">
	<tr>
	<td class="hintergrund"> 
	<table border="0" cellpadding="3" cellspacing="1" bgcolor="#000000" width="100%">
		<tr>
			<th colspan="4" align="left"><?php echo "$sHeader" ?></th>
		</tr>
		<tr>
		<td width="100" align="left">&nbsp;</td>
		<td width="240" align="left">von</td>
		<td width="240" align="left">bis</td>
		<td width="200" align="left">&nbsp;</td>
	</tr>
	<tr>
	<td>
<?php
	$sqlUrlaub = "select schritt_id,bezeichnung from schritt where bezeichnung='Urlaub' or bezeichnung='Krankheit'";
	$rsUrlaub = mysql_query ($sqlUrlaub)
		or die( dbError( $sqlUrlaub ) );
	$selectRow .='<select name="cmbSchritt">';
	while ($myrow = mysql_fetch_array ($rsUrlaub)) {
		$nSchrittId = $myrow["schritt_id"];
		$sSchrittBezeichnung = $myrow["bezeichnung"];
		if ($sSchrittBezeichnung=="Urlaub") {
			$selectRow .='<option value="' . $nSchrittId . '" selected>' . $sSchrittBezeichnung . '</option>';
		}		
		if ($sSchrittBezeichnung=="Krankheit") {
			$selectRow .='<option value="' . $nSchrittId . '">' . $sSchrittBezeichnung . '</option>';
		}
	}
	$selectRow .='</select>';
echo $selectRow;
?>
	</td>
	<td align="left">
	<select name="cmbTag_von">
	<option value="tagvon" selected>Tag</option>
	<option value="01">01</option>
	<option value="02">02</option>
	<option value="03">03</option>
	<option value="04">04</option>
	<option value="05">05</option>
	<option value="06">06</option>
	<option value="07">07</option>
	<option value="08">08</option>
	<option value="09">09</option>
	<option value="10">10</option>
	<option value="11">11</option>
	<option value="12">12</option>
	<option value="13">13</option>
	<option value="14">14</option>
	<option value="15">15</option>
	<option value="16">16</option>
	<option value="17">17</option>
	<option value="18">18</option>
	<option value="19">19</option>
	<option value="20">20</option>
	<option value="21">21</option>
	<option value="22">22</option>
	<option value="23">23</option>
	<option value="24">24</option>
	<option value="25">25</option>
	<option value="26">26</option>
	<option value="27">27</option>
	<option value="28">28</option>
	<option value="29">29</option>
	<option value="30">30</option>
	<option value="31">31</option>
	</select>.

	<select name="cmbMonat_von">
	<option value="monatvon" selected>Monat</option>
	<option value="01">01</option>
	<option value="02">02</option>
	<option value="03">03</option>
	<option value="04">04</option>
	<option value="05">05</option>
	<option value="06">06</option>
	<option value="07">07</option>
	<option value="08">08</option>
	<option value="09">09</option>
	<option value="10">10</option>
	<option value="11">11</option>
	<option value="12">12</option>
	</select>.

	20<input name="txtJahr_von" type="text" size="2" maxlength="2" value=""></td>
	<td align="left">
	<select name="cmbTag_bis">
	<option value="tagbis" selected>Tag</option>
	<option value="01">01</option>
	<option value="02">02</option>
	<option value="03">03</option>
	<option value="04">04</option>
	<option value="05">05</option>
	<option value="06">06</option>
	<option value="07">07</option>
	<option value="08">08</option>
	<option value="09">09</option>
	<option value="10">10</option>
	<option value="11">11</option>
	<option value="12">12</option>
	<option value="13">13</option>
	<option value="14">14</option>
	<option value="15">15</option>
	<option value="16">16</option>
	<option value="17">17</option>
	<option value="18">18</option>
	<option value="19">19</option>
	<option value="20">20</option>
	<option value="21">21</option>
	<option value="22">22</option>
	<option value="23">23</option>
	<option value="24">24</option>
	<option value="25">25</option>
	<option value="26">26</option>
	<option value="27">27</option>
	<option value="28">28</option>
	<option value="29">29</option>
	<option value="30">30</option>
	<option value="31">31</option>
	</select>.

	<select name="cmbMonat_bis">
	<option value="monatbis" selected>Monat</option>
	<option value="01">01</option>
	<option value="02">02</option>
	<option value="03">03</option>
	<option value="04">04</option>
	<option value="05">05</option>
	<option value="06">06</option>
	<option value="07">07</option>
	<option value="08">08</option>
	<option value="09">09</option>
	<option value="10">10</option>
	<option value="11">11</option>
	<option value="12">12</option>
	</select>.
	
	20<input name="txtJahr_bis" type="text" size="2" maxlength="2"></td>
	<td align="left">
<?php
if($bIsSu==true){
	$sqlMitarbeiter = "select ma_id,vorname,name from ma";
	$rsMitarbeiter = mysql_query ($sqlMitarbeiter)
		or die( dbError( $sqlMitarbeiter ) );
	$MaRow .='<select name="cmbMitarbeiter"><option value="" selected>Mitarbeiter eintragen</option>';
	while ($sSelectMitarbeiter = mysql_fetch_array ($rsMitarbeiter)) {
		$nMitarbeiterId=$sSelectMitarbeiter["ma_id"];
		$sVorName=$sSelectMitarbeiter["vorname"];
		$sNachName=$sSelectMitarbeiter["name"];
		$MaRow .='<option value="' . $nMitarbeiterId . '">' . $sVorName . ' ' . $sNachName . '</option>';
	}
	$MaRow .='</select>';
	echo $MaRow;
}
else {
echo "&nbsp;";
}
?>
</td>
	</tr>
	<tr>
		<td colspan="4" align="left"><input type="submit" value="Speichern">&nbsp;&nbsp;&nbsp;&nbsp;<input type="button" onClick="checkAndSubmit()" value="Loeschen"></td>
	</tr>
</table>
</td></tr>
<tr><td>&nbsp;</td></tr>
<tr><td class="hintergrund">
</td></tr></table>
</form>
</table>
</body>
</html>