<?php
	$bIsLocal=true;
	
	$aAccessId=Array();
	$aAccessId[]="3";
	include( "auth.inc" );
	
	include( "arbeit.inc" );
?>
	
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	<title>Staatssicherheit</title>
	<link rel="stylesheet" type="text/css" href="/css/stasi.css">
	<script type="text/javascript" language="JavaScript" src="/js/submit.js"></script>
	<script type="text/javascript" language="JavaScript">
		function closeWindow() {
			if( opener )
				opener.location.reload();
			window.close();
		}
	</script>
	<?php
	
	$bDebug="false";
	if( $txtDelMaId!="" ) {
		//set db connection:
		if( !$bIsDbConnected )
			if( $bIsLocal )
				include("stasi_db_settings.inc");
			else
				include(  "stasi_db_settings.inc" );
		
		//loeschen tabelle arbeit
		$sqlDeleteMa = "delete from arbeit where ma_id=$txtDelMaId";
		mysql_query( $sqlDeleteMa )
			or die( printError( $sqlDeleteMa ) );
		if( $bDebug=="true" )
			echo $sqlDeleteMa . "<br>";
		
		//loeschen tabelle ma
		$sqlDeleteMa = "delete from ma where ma_id=$txtDelMaId";
		mysql_query( $sqlDeleteMa )
			or die( printError( $sqlDeleteMa ) );
		if( $bDebug=="true" )
			echo $sqlDeleteMa . "<br>";
			
		//loeschen tabelle ma_gruppe
		$sqlDeleteMaGruppe = "delete from ma_gruppe where ma_id=$txtDelMaId";
		mysql_query( $sqlDeleteMaGruppe )
			or die( printError( $sqlDeleteMaGruppe ) );
		if( $bDebug=="true" )
			echo $sqlDeleteMaGruppe . "<br>";
		
		//loeschen tabelle ma_projekt	
		$sqlDeleteMaProjekt = "delete from ma_projekt where ma_id=$txtDelMaId";
		mysql_query( $sqlDeleteMaProjekt )
			or die( printError( $sqlDeleteMaProjekt ) );
		if( $bDebug=="true" )
			echo $sqlDeleteMaProjekt . "<br>";
			
		echo "<script type=\"text/javascript\" language=\"JavaScript\">";
		echo "	closeWindow();";
		echo "</script>";
	}
?>
</head>
<body>
<table width="300"><tr><td class="hintergrund">
<table border="0" cellpadding="3" cellspacing="1" width="100%">
<tr>
<td align="center" valign="middle">
<form name="fmDeleteMa" action="<?php echo "$PHP_SELF" ?>" method="post">
	<input type="hidden" name="txtDelMaId" type="hidden" value="<?php echo $txtMaId ?>">
	<table border="0" CELLPADDING="1" CELLSPACING="1" bgcolor="#666666">
		<tr>
			<th align="left" colspan="2">Soll der Mitarbeiter <?php echo "$txtVorname $txtName" ?> gel&ouml;scht werden? Achtung, es werden auch alle Stunden des Mitarbeiters gel&ouml;scht.</td>
		</tr>
		<tr>
			<td><input type="submit" value="Ok"></td>
			<td align='right'><input type="button" value="Cancel" onClick="window.close();"></td>
		</tr>
	</table>
</form>
</td>
</tr>
</table>
</td></tr></table>
</body>
</html>
